inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'lib/schleuder/mail/gpg/sign_part.rb'

Metrics/BlockLength:
  Max: 2700

Metrics/ClassLength:
  Max: 500

Style/StringLiterals:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
